### ISSUE TITLE
run() got an unexpected keyword argument 'auth'

### ISSUE THREAD

**Issue by yunyueshuzhialgorithm** [langchain-ai/research-rabbit#5]
Traceback (most recent call last):
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/bin/langgraph", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/langgraph_cli/analytics.py", line 96, in decorator
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/langgraph_cli/cli.py", line 608, in dev
    run_server(
  File "/root/.cache/uv/archive-v0/J9GbU7R1Db5Xmt1_SrgrO/lib/python3.11/site-packages/langgraph_api/cli.py", line 221, in run_server
    uvicorn.run(
TypeError: run() got an unexpected keyword argument 'auth'

**Comment by hinthornw** [comment]
Hi @yunyueshuzhialgorithm , could you run again using `langgraph-cli==0.1.63`? I believe this should fix things for you
